databases:
  - name: RAMENRAROU_DB
    databaseName: ramentarou_db
    user: RAMENTAROU
    region: singapore

services:
  - type: web
    name: RAMENTAROU
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: RAMENTAROU_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

